### ISSUE TITLE
Do we really need this?

### ISSUE THREAD

**Issue by AaronM04** [go-guru-academy/routermanager#2]
https://github.com/go-guru-academy/routermanager/blob/ec2ce3797b690d34c99ac1366d4a0bfb7c23f431/routermanager.go#L114

**Comment by erich-verys** [comment]
Since we are using string pointers, providing a string to pointer helper function is, well..helpful. AWS has done the same in it's Go SDK.

**Comment by go-guru-academy** [comment]
Since we are using string pointers, providing a string to pointer helper function is, well..helpful. AWS has done the same in it's Go SDK.
